site_name: Intelligence Course
site_url: https://streetfire99.github.io/Intelligence/
repo_url: https://github.com/Streetfire99/Intelligence

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Streetfire99/Intelligence
